//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PageResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string BtLogin {
            get {
                return ResourceManager.GetString("BtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. 27, Ln. 128 Xihe 1st Road, Wujie Township,Yilan County 26847, Taiwan, R.O.C..
        /// </summary>
        internal static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +886-3-965-8899.
        /// </summary>
        internal static string CompanyFax {
            get {
                return ResourceManager.GetString("CompanyFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@sheico.com.tw.
        /// </summary>
        internal static string CompanyMail {
            get {
                return ResourceManager.GetString("CompanyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +886-3-965-6699.
        /// </summary>
        internal static string CompanyTel {
            get {
                return ResourceManager.GetString("CompanyTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHEICO Group.
        /// </summary>
        internal static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: No. 27, Ln. 128 Xihe 1st Road, Wujie Township, Yilan County 26847, Taiwan, R.O.C　TEL.: +886-3-9656699　E-mail: info@sheico.com.tw.
        /// </summary>
        internal static string FooterContact {
            get {
                return ResourceManager.GetString("FooterContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012 Sheico Group. All rights reserved..
        /// </summary>
        internal static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sheico is the global leading supplier in water sports apparel.&lt;/p&gt;
        ///&lt;p&gt;We have over 40 years of experience in neoprene technology and garment manufacturing. With the collaboration of our technical experts and respected customers, Sheico sets the standard for wetsuit innovation. In the past decade, Sheico has also been engaged in the development and production of spandex yarn, performance fabric, active wear, and personal flotation devices.&lt;/p&gt;.
        /// </summary>
        internal static string HomeAd1 {
            get {
                return ResourceManager.GetString("HomeAd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LbAddress {
            get {
                return ResourceManager.GetString("LbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string LbEmail {
            get {
                return ResourceManager.GetString("LbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX..
        /// </summary>
        internal static string LbFax {
            get {
                return ResourceManager.GetString("LbFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string LbForgot {
            get {
                return ResourceManager.GetString("LbForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string LbRegister {
            get {
                return ResourceManager.GetString("LbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string LbRemember {
            get {
                return ResourceManager.GetString("LbRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEL..
        /// </summary>
        internal static string LbTel {
            get {
                return ResourceManager.GetString("LbTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        internal static string LinkLanguage {
            get {
                return ResourceManager.GetString("LinkLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMUNITY.
        /// </summary>
        internal static string MenuCommunity {
            get {
                return ResourceManager.GetString("MenuCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        internal static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSR.
        /// </summary>
        internal static string MenuCsr {
            get {
                return ResourceManager.GetString("MenuCsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG OFF.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS.
        /// </summary>
        internal static string MenuPress {
            get {
                return ResourceManager.GetString("MenuPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        internal static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHEICO Group.
        /// </summary>
        internal static string MetaAuthor {
            get {
                return ResourceManager.GetString("MetaAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHEICO Group.
        /// </summary>
        internal static string MetaCopyright {
            get {
                return ResourceManager.GetString("MetaCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHEICO, Spandex Yarn, Spanflex Fabric, Neoprene Sheets, Wetsuits, Dry Suits, Rash Guards, Personal Flotation Devices, Boots, Gloves, Buoyancy Compensator &amp; Commercial / Military Products.
        /// </summary>
        internal static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHEICO, Spandex Yarn, Spanflex Fabric, Neoprene Sheets, Wetsuits, Dry Suits, Rash Guards, Personal Flotation Devices, Boots, Gloves, Buoyancy Compensator &amp; Commercial / Military Products.
        /// </summary>
        internal static string MetaKeyword {
            get {
                return ResourceManager.GetString("MetaKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHEICO Group.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        internal static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
    }
}
